--
-- PostgreSQL database dump
--

\restrict gQ8CNd3tVgATIkh0OYtcre3nt3BQcbOVI7a3L8iOEjnPV3XIUXKCcYThXiPhzIy

-- Dumped from database version 17.7
-- Dumped by pg_dump version 17.7

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Reservacion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Reservacion" (
    id_reservacion bigint NOT NULL,
    id_alquiler_id bigint
);


ALTER TABLE public."Reservacion" OWNER TO postgres;

--
-- Name: Reservacion_id_reservacion_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Reservacion" ALTER COLUMN id_reservacion ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Reservacion_id_reservacion_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: actas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.actas (
    id_acta bigint NOT NULL,
    id_condominio_id bigint
);


ALTER TABLE public.actas OWNER TO postgres;

--
-- Name: actas_id_acta_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.actas ALTER COLUMN id_acta ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.actas_id_acta_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: alquiler; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.alquiler (
    id_alquiler bigint NOT NULL,
    id_domicilio_id bigint,
    id_noticia_id bigint
);


ALTER TABLE public.alquiler OWNER TO postgres;

--
-- Name: alquiler_id_alquiler_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.alquiler ALTER COLUMN id_alquiler ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.alquiler_id_alquiler_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bancos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.bancos (
    id_banco bigint NOT NULL,
    id_condominio_id bigint
);


ALTER TABLE public.bancos OWNER TO postgres;

--
-- Name: bancos_id_banco_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.bancos ALTER COLUMN id_banco ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bancos_id_banco_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categoria; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categoria (
    id_categoria bigint NOT NULL
);


ALTER TABLE public.categoria OWNER TO postgres;

--
-- Name: categoria_id_categoria_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.categoria ALTER COLUMN id_categoria ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categoria_id_categoria_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cierre_mes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cierre_mes (
    id_cierre bigint NOT NULL,
    id_condominio_id bigint
);


ALTER TABLE public.cierre_mes OWNER TO postgres;

--
-- Name: cierre_mes_id_cierre_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cierre_mes ALTER COLUMN id_cierre ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cierre_mes_id_cierre_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: condominio; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.condominio (
    id_condominio bigint NOT NULL
);


ALTER TABLE public.condominio OWNER TO postgres;

--
-- Name: condominio_id_condominio_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.condominio ALTER COLUMN id_condominio ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.condominio_id_condominio_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cuota_mensual; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cuota_mensual (
    id_cuota_m bigint NOT NULL,
    id_condominio_id bigint
);


ALTER TABLE public.cuota_mensual OWNER TO postgres;

--
-- Name: cuota_mensual_id_cuota_m_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cuota_mensual ALTER COLUMN id_cuota_m ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cuota_mensual_id_cuota_m_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: datos_transaccion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.datos_transaccion (
    id_transaccion bigint NOT NULL,
    id_movimiento_id bigint
);


ALTER TABLE public.datos_transaccion OWNER TO postgres;

--
-- Name: datos_transaccion_id_transaccion_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.datos_transaccion ALTER COLUMN id_transaccion ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.datos_transaccion_id_transaccion_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: deudas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.deudas (
    id_deuda bigint NOT NULL,
    id_domicilio_id bigint
);


ALTER TABLE public.deudas OWNER TO postgres;

--
-- Name: deudas_id_deuda_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.deudas ALTER COLUMN id_deuda ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.deudas_id_deuda_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    content_type_id integer,
    user_id bigint
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_clockedschedule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_beat_clockedschedule (
    id integer NOT NULL
);


ALTER TABLE public.django_celery_beat_clockedschedule OWNER TO postgres;

--
-- Name: django_celery_beat_clockedschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_beat_clockedschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_clockedschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_crontabschedule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_beat_crontabschedule (
    id integer NOT NULL
);


ALTER TABLE public.django_celery_beat_crontabschedule OWNER TO postgres;

--
-- Name: django_celery_beat_crontabschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_beat_crontabschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_crontabschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_intervalschedule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_beat_intervalschedule (
    id integer NOT NULL
);


ALTER TABLE public.django_celery_beat_intervalschedule OWNER TO postgres;

--
-- Name: django_celery_beat_intervalschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_beat_intervalschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_intervalschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_periodictask; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_beat_periodictask (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    clocked_id integer,
    crontab_id integer,
    interval_id integer,
    solar_id integer
);


ALTER TABLE public.django_celery_beat_periodictask OWNER TO postgres;

--
-- Name: django_celery_beat_periodictask_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_beat_periodictask ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_periodictask_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_periodictasks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_beat_periodictasks (
    ident smallint NOT NULL
);


ALTER TABLE public.django_celery_beat_periodictasks OWNER TO postgres;

--
-- Name: django_celery_beat_solarschedule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_beat_solarschedule (
    id integer NOT NULL,
    event character varying(24) NOT NULL,
    latitude numeric(9,6) NOT NULL,
    longitude numeric(9,6) NOT NULL
);


ALTER TABLE public.django_celery_beat_solarschedule OWNER TO postgres;

--
-- Name: django_celery_beat_solarschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_beat_solarschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_solarschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_results_chordcounter; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_results_chordcounter (
    id integer NOT NULL,
    group_id character varying(255) NOT NULL
);


ALTER TABLE public.django_celery_results_chordcounter OWNER TO postgres;

--
-- Name: django_celery_results_chordcounter_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_results_chordcounter ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_results_chordcounter_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_results_groupresult; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_results_groupresult (
    id integer NOT NULL,
    group_id character varying(255) NOT NULL
);


ALTER TABLE public.django_celery_results_groupresult OWNER TO postgres;

--
-- Name: django_celery_results_groupresult_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_results_groupresult ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_results_groupresult_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_results_taskresult; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_results_taskresult (
    id integer NOT NULL,
    task_id character varying(255) NOT NULL
);


ALTER TABLE public.django_celery_results_taskresult OWNER TO postgres;

--
-- Name: django_celery_results_taskresult_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_results_taskresult ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_results_taskresult_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: domicilio; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.domicilio (
    id_domicilio bigint NOT NULL,
    id_condominio_id bigint,
    id_propietario_id bigint,
    id_torre_id bigint
);


ALTER TABLE public.domicilio OWNER TO postgres;

--
-- Name: domicilio_id_domicilio_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.domicilio ALTER COLUMN id_domicilio ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.domicilio_id_domicilio_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: establecimiento_precios; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.establecimiento_precios (
    id bigint NOT NULL,
    id_condominio_id bigint
);


ALTER TABLE public.establecimiento_precios OWNER TO postgres;

--
-- Name: establecimiento_precios_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.establecimiento_precios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.establecimiento_precios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fondos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fondos (
    id_fondo bigint NOT NULL,
    id_movimiento_id bigint
);


ALTER TABLE public.fondos OWNER TO postgres;

--
-- Name: fondos_id_fondo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.fondos ALTER COLUMN id_fondo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fondos_id_fondo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: gastos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.gastos (
    id_gasto bigint NOT NULL,
    id_categoria_id bigint,
    id_movimiento_id bigint
);


ALTER TABLE public.gastos OWNER TO postgres;

--
-- Name: gastos_id_gasto_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.gastos ALTER COLUMN id_gasto ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gastos_id_gasto_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ingresos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ingresos (
    id_ingreso bigint NOT NULL,
    id_movimiento_id bigint,
    id_propietario_id bigint
);


ALTER TABLE public.ingresos OWNER TO postgres;

--
-- Name: ingresos_id_ingreso_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ingresos ALTER COLUMN id_ingreso ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ingresos_id_ingreso_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: movimientos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.movimientos (
    id_movimiento bigint NOT NULL,
    id_banco_id bigint
);


ALTER TABLE public.movimientos OWNER TO postgres;

--
-- Name: movimientos_id_movimiento_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.movimientos ALTER COLUMN id_movimiento ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movimientos_id_movimiento_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: noticia; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.noticia (
    id bigint NOT NULL,
    slug character varying(255) NOT NULL,
    autor_id bigint,
    id_condominio_id bigint
);


ALTER TABLE public.noticia OWNER TO postgres;

--
-- Name: noticia_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.noticia ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.noticia_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: propietario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.propietario (
    id_propietario bigint NOT NULL,
    id_usuario_id bigint
);


ALTER TABLE public.propietario OWNER TO postgres;

--
-- Name: propietario_id_propietario_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.propietario ALTER COLUMN id_propietario ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.propietario_id_propietario_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recargos_y_descuentos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.recargos_y_descuentos (
    id bigint NOT NULL,
    id_condominio_id bigint
);


ALTER TABLE public.recargos_y_descuentos OWNER TO postgres;

--
-- Name: recargos_y_descuentos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.recargos_y_descuentos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recargos_y_descuentos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recibos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.recibos (
    id_recibo bigint NOT NULL,
    id_deuda_id bigint,
    id_movimiento_id bigint
);


ALTER TABLE public.recibos OWNER TO postgres;

--
-- Name: recibos_id_recibo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.recibos ALTER COLUMN id_recibo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recibos_id_recibo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    id_rol bigint NOT NULL
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- Name: roles_id_rol_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.roles ALTER COLUMN id_rol ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_rol_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tasas_de_cambio; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tasas_de_cambio (
    id bigint NOT NULL
);


ALTER TABLE public.tasas_de_cambio OWNER TO postgres;

--
-- Name: tasas_de_cambio_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tasas_de_cambio ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tasas_de_cambio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: torre; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.torre (
    id_torre bigint NOT NULL,
    id_condominio_id bigint
);


ALTER TABLE public.torre OWNER TO postgres;

--
-- Name: torre_id_torre_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.torre ALTER COLUMN id_torre ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.torre_id_torre_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuarios (
    id bigint NOT NULL,
    email character varying(254) NOT NULL,
    username character varying(150) NOT NULL,
    id_condominio_id bigint,
    id_rol_id bigint
);


ALTER TABLE public.usuarios OWNER TO postgres;

--
-- Name: usuarios_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Reservacion Reservacion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Reservacion"
    ADD CONSTRAINT "Reservacion_pkey" PRIMARY KEY (id_reservacion);


--
-- Name: actas actas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.actas
    ADD CONSTRAINT actas_pkey PRIMARY KEY (id_acta);


--
-- Name: alquiler alquiler_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.alquiler
    ADD CONSTRAINT alquiler_pkey PRIMARY KEY (id_alquiler);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: bancos bancos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bancos
    ADD CONSTRAINT bancos_pkey PRIMARY KEY (id_banco);


--
-- Name: categoria categoria_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categoria
    ADD CONSTRAINT categoria_pkey PRIMARY KEY (id_categoria);


--
-- Name: cierre_mes condominio_app_cierre_mes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cierre_mes
    ADD CONSTRAINT condominio_app_cierre_mes_pkey PRIMARY KEY (id_cierre);


--
-- Name: fondos condominio_app_fondos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fondos
    ADD CONSTRAINT condominio_app_fondos_pkey PRIMARY KEY (id_fondo);


--
-- Name: condominio configuracion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.condominio
    ADD CONSTRAINT configuracion_pkey PRIMARY KEY (id_condominio);


--
-- Name: cuota_mensual cuota_mensual_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuota_mensual
    ADD CONSTRAINT cuota_mensual_pkey PRIMARY KEY (id_cuota_m);


--
-- Name: datos_transaccion datos_transaccion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.datos_transaccion
    ADD CONSTRAINT datos_transaccion_pkey PRIMARY KEY (id_transaccion);


--
-- Name: deudas deudas_pkey1; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.deudas
    ADD CONSTRAINT deudas_pkey1 PRIMARY KEY (id_deuda);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_clockedschedule django_celery_beat_clockedschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_clockedschedule
    ADD CONSTRAINT django_celery_beat_clockedschedule_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_crontabschedule django_celery_beat_crontabschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_crontabschedule
    ADD CONSTRAINT django_celery_beat_crontabschedule_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_intervalschedule django_celery_beat_intervalschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_intervalschedule
    ADD CONSTRAINT django_celery_beat_intervalschedule_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_periodictask django_celery_beat_periodictask_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_periodictask_name_key UNIQUE (name);


--
-- Name: django_celery_beat_periodictask django_celery_beat_periodictask_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_periodictask_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_periodictasks django_celery_beat_periodictasks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictasks
    ADD CONSTRAINT django_celery_beat_periodictasks_pkey PRIMARY KEY (ident);


--
-- Name: django_celery_beat_solarschedule django_celery_beat_solar_event_latitude_longitude_ba64999a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_solarschedule
    ADD CONSTRAINT django_celery_beat_solar_event_latitude_longitude_ba64999a_uniq UNIQUE (event, latitude, longitude);


--
-- Name: django_celery_beat_solarschedule django_celery_beat_solarschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_solarschedule
    ADD CONSTRAINT django_celery_beat_solarschedule_pkey PRIMARY KEY (id);


--
-- Name: django_celery_results_chordcounter django_celery_results_chordcounter_group_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_results_chordcounter
    ADD CONSTRAINT django_celery_results_chordcounter_group_id_key UNIQUE (group_id);


--
-- Name: django_celery_results_chordcounter django_celery_results_chordcounter_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_results_chordcounter
    ADD CONSTRAINT django_celery_results_chordcounter_pkey PRIMARY KEY (id);


--
-- Name: django_celery_results_groupresult django_celery_results_groupresult_group_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_results_groupresult
    ADD CONSTRAINT django_celery_results_groupresult_group_id_key UNIQUE (group_id);


--
-- Name: django_celery_results_groupresult django_celery_results_groupresult_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_results_groupresult
    ADD CONSTRAINT django_celery_results_groupresult_pkey PRIMARY KEY (id);


--
-- Name: django_celery_results_taskresult django_celery_results_taskresult_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_results_taskresult
    ADD CONSTRAINT django_celery_results_taskresult_pkey PRIMARY KEY (id);


--
-- Name: django_celery_results_taskresult django_celery_results_taskresult_task_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_results_taskresult
    ADD CONSTRAINT django_celery_results_taskresult_task_id_key UNIQUE (task_id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: domicilio domicilio_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.domicilio
    ADD CONSTRAINT domicilio_pkey PRIMARY KEY (id_domicilio);


--
-- Name: establecimiento_precios establecimiento_precios_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.establecimiento_precios
    ADD CONSTRAINT establecimiento_precios_pkey PRIMARY KEY (id);


--
-- Name: gastos gastos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.gastos
    ADD CONSTRAINT gastos_pkey PRIMARY KEY (id_gasto);


--
-- Name: ingresos ingresos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ingresos
    ADD CONSTRAINT ingresos_pkey PRIMARY KEY (id_ingreso);


--
-- Name: movimientos movimientos_bancarios_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movimientos
    ADD CONSTRAINT movimientos_bancarios_pkey PRIMARY KEY (id_movimiento);


--
-- Name: noticia noticia_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.noticia
    ADD CONSTRAINT noticia_pkey PRIMARY KEY (id);


--
-- Name: noticia noticia_slug_fe7427a1_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.noticia
    ADD CONSTRAINT noticia_slug_fe7427a1_uniq UNIQUE (slug);


--
-- Name: propietario propietario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.propietario
    ADD CONSTRAINT propietario_pkey PRIMARY KEY (id_propietario);


--
-- Name: recargos_y_descuentos recargos_y_descuentos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.recargos_y_descuentos
    ADD CONSTRAINT recargos_y_descuentos_pkey PRIMARY KEY (id);


--
-- Name: recibos recibos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.recibos
    ADD CONSTRAINT recibos_pkey PRIMARY KEY (id_recibo);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id_rol);


--
-- Name: tasas_de_cambio tasas_de_cambio_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasas_de_cambio
    ADD CONSTRAINT tasas_de_cambio_pkey PRIMARY KEY (id);


--
-- Name: torre torre_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.torre
    ADD CONSTRAINT torre_pkey PRIMARY KEY (id_torre);


--
-- Name: usuarios usuarios_email_ef44a1d6_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_email_ef44a1d6_uniq UNIQUE (email);


--
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);


--
-- Name: usuarios usuarios_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_username_key UNIQUE (username);


--
-- Name: Reservacion_id_alquiler_id_cc74971f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "Reservacion_id_alquiler_id_cc74971f" ON public."Reservacion" USING btree (id_alquiler_id);


--
-- Name: actas_id_condominio_id_fb9845a1; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX actas_id_condominio_id_fb9845a1 ON public.actas USING btree (id_condominio_id);


--
-- Name: alquiler_id_domicilio_id_276eef56; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX alquiler_id_domicilio_id_276eef56 ON public.alquiler USING btree (id_domicilio_id);


--
-- Name: alquiler_id_noticia_id_7b6e8830; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX alquiler_id_noticia_id_7b6e8830 ON public.alquiler USING btree (id_noticia_id);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: bancos_id_condominio_id_5c79fd03; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX bancos_id_condominio_id_5c79fd03 ON public.bancos USING btree (id_condominio_id);


--
-- Name: condominio_app_cierre_mes_id_condominio_id_47e0d8ab; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX condominio_app_cierre_mes_id_condominio_id_47e0d8ab ON public.cierre_mes USING btree (id_condominio_id);


--
-- Name: cuota_mensual_id_condominio_id_a44f8716; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cuota_mensual_id_condominio_id_a44f8716 ON public.cuota_mensual USING btree (id_condominio_id);


--
-- Name: datos_transaccion_id_movimiento_id_ec347699; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX datos_transaccion_id_movimiento_id_ec347699 ON public.datos_transaccion USING btree (id_movimiento_id);


--
-- Name: deudas_id_domicilio_id_0b4bd904; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX deudas_id_domicilio_id_0b4bd904 ON public.deudas USING btree (id_domicilio_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_celery_beat_periodictask_clocked_id_47a69f82; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_celery_beat_periodictask_clocked_id_47a69f82 ON public.django_celery_beat_periodictask USING btree (clocked_id);


--
-- Name: django_celery_beat_periodictask_crontab_id_d3cba168; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_celery_beat_periodictask_crontab_id_d3cba168 ON public.django_celery_beat_periodictask USING btree (crontab_id);


--
-- Name: django_celery_beat_periodictask_interval_id_a8ca27da; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_celery_beat_periodictask_interval_id_a8ca27da ON public.django_celery_beat_periodictask USING btree (interval_id);


--
-- Name: django_celery_beat_periodictask_solar_id_a87ce72c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_celery_beat_periodictask_solar_id_a87ce72c ON public.django_celery_beat_periodictask USING btree (solar_id);


--
-- Name: domicilio_id_condominio_id_8f872c84; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX domicilio_id_condominio_id_8f872c84 ON public.domicilio USING btree (id_condominio_id);


--
-- Name: domicilio_id_propietario_id_1d484c7f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX domicilio_id_propietario_id_1d484c7f ON public.domicilio USING btree (id_propietario_id);


--
-- Name: domicilio_id_torre_id_6b5483f2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX domicilio_id_torre_id_6b5483f2 ON public.domicilio USING btree (id_torre_id);


--
-- Name: establecimiento_precios_id_condominio_id_8d416973; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX establecimiento_precios_id_condominio_id_8d416973 ON public.establecimiento_precios USING btree (id_condominio_id);


--
-- Name: fondos_id_movimiento_id_a0146c21; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fondos_id_movimiento_id_a0146c21 ON public.fondos USING btree (id_movimiento_id);


--
-- Name: gastos_id_categoria_id_afdae726; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX gastos_id_categoria_id_afdae726 ON public.gastos USING btree (id_categoria_id);


--
-- Name: gastos_id_movimiento_id_dbeee35c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX gastos_id_movimiento_id_dbeee35c ON public.gastos USING btree (id_movimiento_id);


--
-- Name: ingresos_id_movimiento_id_d4b65022; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ingresos_id_movimiento_id_d4b65022 ON public.ingresos USING btree (id_movimiento_id);


--
-- Name: ingresos_id_propietario_id_930a0a7d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ingresos_id_propietario_id_930a0a7d ON public.ingresos USING btree (id_propietario_id);


--
-- Name: movimientos_bancarios_id_banco_id_3e690465; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX movimientos_bancarios_id_banco_id_3e690465 ON public.movimientos USING btree (id_banco_id);


--
-- Name: noticia_autor_id_db7cadf7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX noticia_autor_id_db7cadf7 ON public.noticia USING btree (autor_id);


--
-- Name: noticia_id_condominio_id_7102599f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX noticia_id_condominio_id_7102599f ON public.noticia USING btree (id_condominio_id);


--
-- Name: propietario_id_usuario_id_f774a63c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX propietario_id_usuario_id_f774a63c ON public.propietario USING btree (id_usuario_id);


--
-- Name: recargos_y_descuentos_id_condominio_id_b34ffc55; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX recargos_y_descuentos_id_condominio_id_b34ffc55 ON public.recargos_y_descuentos USING btree (id_condominio_id);


--
-- Name: recibos_id_deuda_id_09d12803; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX recibos_id_deuda_id_09d12803 ON public.recibos USING btree (id_deuda_id);


--
-- Name: recibos_id_movimiento_id_0e9f90a0; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX recibos_id_movimiento_id_0e9f90a0 ON public.recibos USING btree (id_movimiento_id);


--
-- Name: torre_id_condominio_id_fdde9a52; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX torre_id_condominio_id_fdde9a52 ON public.torre USING btree (id_condominio_id);


--
-- Name: usuarios_id_condominio_id_b7a64828; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX usuarios_id_condominio_id_b7a64828 ON public.usuarios USING btree (id_condominio_id);


--
-- Name: usuarios_id_rol_id_2dbc56ef; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX usuarios_id_rol_id_2dbc56ef ON public.usuarios USING btree (id_rol_id);


--
-- Name: Reservacion Reservacion_id_alquiler_id_cc74971f_fk_alquiler_id_alquiler; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Reservacion"
    ADD CONSTRAINT "Reservacion_id_alquiler_id_cc74971f_fk_alquiler_id_alquiler" FOREIGN KEY (id_alquiler_id) REFERENCES public.alquiler(id_alquiler) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: actas actas_id_condominio_id_fb9845a1_fk_condominio_id_condominio; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.actas
    ADD CONSTRAINT actas_id_condominio_id_fb9845a1_fk_condominio_id_condominio FOREIGN KEY (id_condominio_id) REFERENCES public.condominio(id_condominio) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: alquiler alquiler_id_domicilio_id_276eef56_fk_domicilio_id_domicilio; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.alquiler
    ADD CONSTRAINT alquiler_id_domicilio_id_276eef56_fk_domicilio_id_domicilio FOREIGN KEY (id_domicilio_id) REFERENCES public.domicilio(id_domicilio) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: alquiler alquiler_id_noticia_id_7b6e8830_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.alquiler
    ADD CONSTRAINT alquiler_id_noticia_id_7b6e8830_fk FOREIGN KEY (id_noticia_id) REFERENCES public.noticia(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bancos bancos_id_condominio_id_5c79fd03_fk_condominio_id_condominio; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bancos
    ADD CONSTRAINT bancos_id_condominio_id_5c79fd03_fk_condominio_id_condominio FOREIGN KEY (id_condominio_id) REFERENCES public.condominio(id_condominio) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cierre_mes condominio_app_cierr_id_condominio_id_47e0d8ab_fk_condomini; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cierre_mes
    ADD CONSTRAINT condominio_app_cierr_id_condominio_id_47e0d8ab_fk_condomini FOREIGN KEY (id_condominio_id) REFERENCES public.condominio(id_condominio) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cuota_mensual cuota_mensual_id_condominio_id_a44f8716_fk_condomini; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cuota_mensual
    ADD CONSTRAINT cuota_mensual_id_condominio_id_a44f8716_fk_condomini FOREIGN KEY (id_condominio_id) REFERENCES public.condominio(id_condominio) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: datos_transaccion datos_transaccion_id_movimiento_id_ec347699_fk_movimient; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.datos_transaccion
    ADD CONSTRAINT datos_transaccion_id_movimiento_id_ec347699_fk_movimient FOREIGN KEY (id_movimiento_id) REFERENCES public.movimientos(id_movimiento) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: deudas deudas_id_domicilio_id_0b4bd904_fk_domicilio_id_domicilio; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.deudas
    ADD CONSTRAINT deudas_id_domicilio_id_0b4bd904_fk_domicilio_id_domicilio FOREIGN KEY (id_domicilio_id) REFERENCES public.domicilio(id_domicilio) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_usuarios_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_usuarios_id FOREIGN KEY (user_id) REFERENCES public.usuarios(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_clocked_id_47a69f82_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_clocked_id_47a69f82_fk_django_ce FOREIGN KEY (clocked_id) REFERENCES public.django_celery_beat_clockedschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_crontab_id_d3cba168_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_crontab_id_d3cba168_fk_django_ce FOREIGN KEY (crontab_id) REFERENCES public.django_celery_beat_crontabschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_interval_id_a8ca27da_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_interval_id_a8ca27da_fk_django_ce FOREIGN KEY (interval_id) REFERENCES public.django_celery_beat_intervalschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_solar_id_a87ce72c_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_solar_id_a87ce72c_fk_django_ce FOREIGN KEY (solar_id) REFERENCES public.django_celery_beat_solarschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: domicilio domicilio_id_condominio_id_8f872c84_fk_condominio_id_condominio; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.domicilio
    ADD CONSTRAINT domicilio_id_condominio_id_8f872c84_fk_condominio_id_condominio FOREIGN KEY (id_condominio_id) REFERENCES public.condominio(id_condominio) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: domicilio domicilio_id_propietario_id_1d484c7f_fk_propietar; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.domicilio
    ADD CONSTRAINT domicilio_id_propietario_id_1d484c7f_fk_propietar FOREIGN KEY (id_propietario_id) REFERENCES public.propietario(id_propietario) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: domicilio domicilio_id_torre_id_6b5483f2_fk_torre_id_torre; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.domicilio
    ADD CONSTRAINT domicilio_id_torre_id_6b5483f2_fk_torre_id_torre FOREIGN KEY (id_torre_id) REFERENCES public.torre(id_torre) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: establecimiento_precios establecimiento_prec_id_condominio_id_8d416973_fk_condomini; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.establecimiento_precios
    ADD CONSTRAINT establecimiento_prec_id_condominio_id_8d416973_fk_condomini FOREIGN KEY (id_condominio_id) REFERENCES public.condominio(id_condominio) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: fondos fondos_id_movimiento_id_a0146c21_fk_movimient; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fondos
    ADD CONSTRAINT fondos_id_movimiento_id_a0146c21_fk_movimient FOREIGN KEY (id_movimiento_id) REFERENCES public.movimientos(id_movimiento) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: gastos gastos_id_categoria_id_afdae726_fk_categoria_id_categoria; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.gastos
    ADD CONSTRAINT gastos_id_categoria_id_afdae726_fk_categoria_id_categoria FOREIGN KEY (id_categoria_id) REFERENCES public.categoria(id_categoria) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: gastos gastos_id_movimiento_id_dbeee35c_fk_movimient; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.gastos
    ADD CONSTRAINT gastos_id_movimiento_id_dbeee35c_fk_movimient FOREIGN KEY (id_movimiento_id) REFERENCES public.movimientos(id_movimiento) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ingresos ingresos_id_movimiento_id_d4b65022_fk_movimient; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ingresos
    ADD CONSTRAINT ingresos_id_movimiento_id_d4b65022_fk_movimient FOREIGN KEY (id_movimiento_id) REFERENCES public.movimientos(id_movimiento) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ingresos ingresos_id_propietario_id_930a0a7d_fk_propietar; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ingresos
    ADD CONSTRAINT ingresos_id_propietario_id_930a0a7d_fk_propietar FOREIGN KEY (id_propietario_id) REFERENCES public.propietario(id_propietario) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: movimientos movimientos_bancarios_id_banco_id_3e690465_fk_bancos_id_banco; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movimientos
    ADD CONSTRAINT movimientos_bancarios_id_banco_id_3e690465_fk_bancos_id_banco FOREIGN KEY (id_banco_id) REFERENCES public.bancos(id_banco) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: noticia noticia_autor_id_db7cadf7_fk_usuarios_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.noticia
    ADD CONSTRAINT noticia_autor_id_db7cadf7_fk_usuarios_id FOREIGN KEY (autor_id) REFERENCES public.usuarios(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: noticia noticia_id_condominio_id_7102599f_fk_condominio_id_condominio; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.noticia
    ADD CONSTRAINT noticia_id_condominio_id_7102599f_fk_condominio_id_condominio FOREIGN KEY (id_condominio_id) REFERENCES public.condominio(id_condominio) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: propietario propietario_id_usuario_id_f774a63c_fk_usuarios_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.propietario
    ADD CONSTRAINT propietario_id_usuario_id_f774a63c_fk_usuarios_id FOREIGN KEY (id_usuario_id) REFERENCES public.usuarios(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: recargos_y_descuentos recargos_y_descuento_id_condominio_id_b34ffc55_fk_condomini; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.recargos_y_descuentos
    ADD CONSTRAINT recargos_y_descuento_id_condominio_id_b34ffc55_fk_condomini FOREIGN KEY (id_condominio_id) REFERENCES public.condominio(id_condominio) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: recibos recibos_id_deuda_id_09d12803_fk_deudas_id_deuda; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.recibos
    ADD CONSTRAINT recibos_id_deuda_id_09d12803_fk_deudas_id_deuda FOREIGN KEY (id_deuda_id) REFERENCES public.deudas(id_deuda) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: recibos recibos_id_movimiento_id_0e9f90a0_fk_movimient; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.recibos
    ADD CONSTRAINT recibos_id_movimiento_id_0e9f90a0_fk_movimient FOREIGN KEY (id_movimiento_id) REFERENCES public.movimientos(id_movimiento) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: torre torre_id_condominio_id_fdde9a52_fk_condominio_id_condominio; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.torre
    ADD CONSTRAINT torre_id_condominio_id_fdde9a52_fk_condominio_id_condominio FOREIGN KEY (id_condominio_id) REFERENCES public.condominio(id_condominio) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: usuarios usuarios_id_condominio_id_b7a64828_fk_condominio_id_condominio; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_id_condominio_id_b7a64828_fk_condominio_id_condominio FOREIGN KEY (id_condominio_id) REFERENCES public.condominio(id_condominio) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: usuarios usuarios_id_rol_id_2dbc56ef_fk_roles_id_rol; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_id_rol_id_2dbc56ef_fk_roles_id_rol FOREIGN KEY (id_rol_id) REFERENCES public.roles(id_rol) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict gQ8CNd3tVgATIkh0OYtcre3nt3BQcbOVI7a3L8iOEjnPV3XIUXKCcYThXiPhzIy

